name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  REDIS_HOST: localhost
  REDIS_PORT: 6379
  BASIC_SIZE: 5
  PRO_SIZE: 10
  MONTHLY_LIMIT_MULTIPLIER: 5
  MAX_REQUESTS_PER_MINUTE: 100

jobs:
  build:
    runs-on: ubuntu-latest

    # Define the Redis service
    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install
